### ISSUE TITLE
Parser fails on Ruby 2.0

### ISSUE THREAD

**Issue by Sharpie** [Sharpie/puppet-profile-parser#12]
Running the profile parser under Ruby 2.0 fails when converting Regex matches to a data Hash:

```
[root@pe-20181nightly-master puppet-profile-parser]# ./puppet-profile-parser.rb /vagrant/puppetserver.log --debug
ERROR NoMethodError: undefined method `to_h' for #<Array:0x0000000193ea08>
	./puppet-profile-parser.rb:533:in `convert_match'
	./puppet-profile-parser.rb:590:in `parse_line'
	./puppet-profile-parser.rb:570:in `block in parse_file'
	./puppet-profile-parser.rb:567:in `each_line'
	./puppet-profile-parser.rb:567:in `parse_file'
	./puppet-profile-parser.rb:974:in `block in run'
	./puppet-profile-parser.rb:974:in `each'
	./puppet-profile-parser.rb:974:in `run'
	./puppet-profile-parser.rb:993:in `<main>'
```

This occurs because the `.to_h` method wasn't added to the Array class until Ruby 2.1.

**Comment by Sharpie** [comment]
Two possible resolutions to this issue:

  - Add a Ruby version check and throw an error during startup if the Ruby version is too old.

  - Drop the lower bound on the test suite to Ruby 2.0 and fix any issues that pop up.

The first option would be the easiest to implement. The second option may be better as it would remove some common snags that arise from platforms like CentOS 7 shipping an ancient Ruby.
